{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d6cdb14-35e4-4157-a01a-3b1a8c2e93c1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f2158da2-87b8-4d0e-84d3-46c6c38718da",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Simulation 1: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 1000m m\n",
      "Width : 800m m\n",
      "\n",
      "Simulation 2: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 1000m m\n",
      "Width : 800m m\n",
      "\n",
      "Simulation 3: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 4: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 12080 m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 5: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 6: \n",
      "Environment: Underground\n",
      "Depth: 200m m\n",
      "Length: 12081 m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 7: \n",
      "Environment: Underground\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 8: \n",
      "Environment: Underground\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 9: \n",
      "Environment: Underground\n",
      "Depth: 800m m\n",
      "Length: 500m m\n",
      "Width : 10m m\n",
      "\n",
      "Simulation 10: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n",
      "Simulation 11: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n",
      "Simulation 12: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n",
      "Simulation 13: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n",
      "Simulation 14: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# develop environment specs\n",
    "import csv\n",
    "import pandas as pd\n",
    "# creating class\n",
    "class Environment:\n",
    "    def __init__(self, type, depth, length, width):# creating constructor\n",
    "        self.type = type\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width= width\n",
    "    def get_environment_specs(self):# function to environment_specs\n",
    "        return {\n",
    "            'depth': self.depth,\n",
    "            'length': self.length,\n",
    "            'width': self.width\n",
    "        }\n",
    "class MiningSimulation:# creating mining simulation\n",
    "    def __init__(self, environment):# creating constructor\n",
    "        self.environment = environment\n",
    "def read_data_from_file(file_path):\n",
    "    with open(file_path, 'r') as csv_file:\n",
    "        reader = csv.DictReader(csv_file)\n",
    "        environments=[]\n",
    "        for row in reader:\n",
    "            environment=Environment(\n",
    "                type=row['Type'],\n",
    "                depth=row['Depth'],\n",
    "                length=row['Length'],\n",
    "                width=row['Width']\n",
    "            )\n",
    "            environments.append(environment)\n",
    "        return environments\n",
    "# Read data from CSV file\n",
    "environments = read_data_from_file('simulation.csv')\n",
    "# Initialize Simulation\n",
    "mine_simulations = []\n",
    "for environment in environments:\n",
    "    mine_simulation=MiningSimulation(environment)\n",
    "    mine_simulations.append(mine_simulation)\n",
    "#print environment specs for each simulation\n",
    "for i, mine_simulation in enumerate(mine_simulations):\n",
    "    environment_specs=mine_simulation.environment.get_environment_specs()\n",
    "    print(f\"Simulation {i+1}: \")\n",
    "    print(f\"Environment: {mine_simulation.environment.type}\")\n",
    "    print(f\"Depth: {environment_specs['depth']} m\")\n",
    "    print(f\"Length: {environment_specs['length']} m\")\n",
    "    print(f\"Width : {environment_specs['width']} m\")\n",
    "    print()\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9191bd2-dfe5-4022-95fc-cefb807ce7cf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9fad4f24-a7e2-4be1-ab92-fb1b4e94bbc4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Simulation 1:\n",
      "Drilling operation initiated in Rotary Surface section with Drill1 1\n",
      "Environment specifications: Depth=200m, Length=1000m, Width=800m\n",
      "\n",
      "Simulation 2:\n",
      "Drilling operation initiated in Hammer Surface section with Drill2 2\n",
      "Environment specifications: Depth=200m, Length=1000m, Width=800m\n",
      "\n",
      "Simulation 3:\n",
      "Hauling operation initiated in Diesel Surface section with Truck1 1\n",
      "Environment specifications: Depth=200m, Length=10250m, Width=400m \n",
      "\n",
      "Simulation 4:\n",
      "Hauling operation initiated in Diesel Surface section with Truck1 1\n",
      "Environment specifications: Depth=200m, Length=12080, Width=400m \n",
      "\n",
      "Simulation 5:\n",
      "Hauling operation initiated in Diesel Surface section with Truck2 2\n",
      "Environment specifications: Depth=200m, Length=10250m, Width=400m \n",
      "\n",
      "Simulation 6:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 7:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 8:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 9:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 10:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 11:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 12:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 13:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 14:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Number of environments: 14\n",
      "Number of equipment data: 14\n",
      "Number of mine simulations: 14\n"
     ]
    }
   ],
   "source": [
    "#Develop integration with drilling, hauling\n",
    "import csv\n",
    "import pandas as pd\n",
    "class Environment:\n",
    "    def __init__(self, type, depth, length, width, type_of_section):\n",
    "        self.type = type\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width = width\n",
    "        self.type_of_section = type_of_section\n",
    "    def get_environment_specs(self):\n",
    "        return {\n",
    "            'type': self.type,\n",
    "            'depth': self.depth,\n",
    "            'length': self.length,\n",
    "            'width': self.width,\n",
    "            'type_of_section': self.type_of_section\n",
    "        }\n",
    "class Equipment:\n",
    "    def __init__(self, equipment_type, capacity, power, section, type_of_section, depth, length, width, utilization, mtbf, mttr):\n",
    "        self.equipment_type = equipment_type\n",
    "        self.capacity = capacity\n",
    "        self.power = power\n",
    "        self.section = section\n",
    "        self.type_of_section = type_of_section\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width = width\n",
    "        self.utilization = utilization\n",
    "        self.mtbf = mtbf\n",
    "        self.mttr = mttr\n",
    "class MiningSimulation:\n",
    "    def __init__(self, environment, equipment):\n",
    "        self.environment = environment\n",
    "        self.equipment = equipment\n",
    "    def perform_operations(self):\n",
    "        equipment_type_str = str(self.equipment.equipment_type).lower()\n",
    "        if equipment_type_str.startswith(\"drill\"):\n",
    "            self.drill()\n",
    "        elif equipment_type_str.startswith(\"truck\"):\n",
    "            self.haul()\n",
    "        else:\n",
    "            print(\"No valid operation specified for the given equipment.\")\n",
    "    def drill(self):\n",
    "        specs = self.environment.get_environment_specs()\n",
    "        print(f\"Drilling operation initiated in {specs['type']} {specs['type_of_section']} section with {self.equipment.equipment_type} {self.equipment.equipment_type[-1]}\")\n",
    "        print(f\"Environment specifications: Depth={specs['depth']}, Length={specs['length']}, Width={specs['width']}\")\n",
    "    def haul(self):\n",
    "        specs = self.environment.get_environment_specs()\n",
    "        print(f\"Hauling operation initiated in {specs['type']} {specs['type_of_section']} section with {self.equipment.equipment_type} {self.equipment.equipment_type[-1]}\")\n",
    "        print(f\"Environment specifications: Depth={specs['depth']}, Length={specs['length']}, Width={specs['width']}\")\n",
    "def read_data_from_file(file_path):\n",
    "    environments = []\n",
    "    equipment_data = []\n",
    "    try:\n",
    "        data = pd.read_csv(file_path)\n",
    "        for _, row in data.iterrows():\n",
    "            environment = Environment(\n",
    "                type=row['Type of Equipment'],\n",
    "                depth=row['Depth'],\n",
    "                length=row['Length'],\n",
    "                width=row['Width'],\n",
    "                type_of_section=row['Type of section']\n",
    "            )\n",
    "            environments.append(environment)\n",
    "            equipment = Equipment(\n",
    "                equipment_type=row['Equipment'],\n",
    "                capacity=row['Capacity'],\n",
    "                power=row['Power'],\n",
    "                section=row['Section'],\n",
    "                type_of_section=row['Type of section'],\n",
    "                depth=row['Depth'],\n",
    "                length=row['Length'],\n",
    "                width=row['Width'],\n",
    "                utilization=row['Utilization'],\n",
    "                mtbf=row['MTBF'],\n",
    "                mttr=row['MTTR']\n",
    "            )\n",
    "            equipment_data.append(equipment)\n",
    "    except Exception as e:\n",
    "        print(\"Error reading data from CSV:\", e)\n",
    "    return environments, equipment_data\n",
    "# Read data from CSV file\n",
    "file_path = 'simulation1.csv'\n",
    "environments, equipment_data = read_data_from_file(file_path)\n",
    "# Initialize Simulation for each environment and equipment\n",
    "mine_simulations = [MiningSimulation(env, equipment) for env, equipment in zip(environments, equipment_data)]\n",
    "# Perform operations for each Simulation\n",
    "for i, mine_simulation in enumerate(mine_simulations):\n",
    "    print(f\"Simulation {i + 1}:\")\n",
    "    mine_simulation.perform_operations()\n",
    "    print()\n",
    "# Debug prints to investigate\n",
    "print(f\"Number of environments: {len(environments)}\")\n",
    "print(f\"Number of equipment data: {len(equipment_data)}\")\n",
    "print(f\"Number of mine simulations: {len(mine_simulations)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6713875e-9306-413d-bc05-1e9acecfe152",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b819d730-b287-4d36-bafa-c277174d13b1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7b1ddd01-9755-4354-9dbd-66264057fd0b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 1000m m\n",
      "Width: 800m m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 1000m m\n",
      "Width: 800m m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 12080 m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "West Mining Section\n",
      "Section: West and Type of section: Underground\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 12081 m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "West Mining Section\n",
      "Section: West and Type of section: Underground\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "West Mining Section\n",
      "Section: West and Type of section: Underground\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "West Mining Section\n",
      "Section: West and Type of section: Underground\n",
      "Environment Specifications:\n",
      "Depth: 800m m\n",
      "Length: 500m m\n",
      "Width: 10m m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "import pandas as pd\n",
    "class Environment:\n",
    "    def __init__(self, section, type_of_section, depth, length, width):\n",
    "        self.section = section\n",
    "        self.type_of_section = type_of_section\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width = width\n",
    "    def get_environment_specs(self):\n",
    "        return {\n",
    "            'depth': self.depth,\n",
    "            'length': self.length,\n",
    "            'width': self.width\n",
    "        }\n",
    "class MiningSimulation:\n",
    "    def __init__(self, environment):\n",
    "        self.environment = environment\n",
    "    def drill(self):\n",
    "        # Placeholder for drilling functionality\n",
    "        print(\"Drilling operation initiated in\", self.environment.section)\n",
    "    def haul(self):\n",
    "        # Placeholder for hauling functionality\n",
    "        print(\"Hauling operation initiated in\", self.environment.section)\n",
    "class MiningSection:\n",
    "    def __init__(self, environment):\n",
    "        self.environment = environment\n",
    "        self.operations = {'drilling': 1, 'hauling': 1}  # Placeholder values\n",
    "    def get_section_info(self):\n",
    "        environment_specs = self.environment.get_environment_specs()\n",
    "        section_info = f\"{self.environment.section} Mining Section\"\n",
    "        section_info += f\"\\nSection: {self.environment.section} and Type of section: {self.environment.type_of_section}\"\n",
    "        section_info += \"\\nEnvironment Specifications:\"\n",
    "        section_info += f\"\\nDepth: {environment_specs['depth']} m\"\n",
    "        section_info += f\"\\nLength: {environment_specs['length']} m\"\n",
    "        section_info += f\"\\nWidth: {environment_specs['width']} m\"\n",
    "        section_info += \"\\n\\nMining Operations:\"\n",
    "        section_info += \"\\nDrilling operation initiated\"\n",
    "        section_info += \"\\nHauling operation initiated\\n\"\n",
    "        return section_info\n",
    "def read_data_from_file(file_path):\n",
    "    environments = []\n",
    "    try:\n",
    "        data = pd.read_csv(file_path)\n",
    "        for _, row in data.iterrows():\n",
    "            environment = Environment(\n",
    "                section=row['Section'],\n",
    "                type_of_section=row['Type of section'],\n",
    "                depth=(row['Depth']),\n",
    "                length=(row['Length']),\n",
    "                width=(row['Width'])\n",
    "            )\n",
    "            environments.append(environment)\n",
    "    except Exception as e:\n",
    "        print(\"Error reading data from CSV:\", e)\n",
    "    return environments\n",
    "# Read data from CSV file\n",
    "file_path = 'simulation1.csv'\n",
    "environments = read_data_from_file(file_path)\n",
    "# Initialize MiningSection for each environment\n",
    "mining_sections = [MiningSection(env) for env in environments]\n",
    "# Print information for each mining section\n",
    "for mining_section in mining_sections:\n",
    "    print(mining_section.get_section_info())\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb345302-6707-4683-94a8-323556524735",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
